import type { NextConfig } from "next";
import legacyRedirects from "./lib/data/legacyRedirects.json";

const nextConfig: NextConfig = {
  devIndicators: false,
  experimental: {
    serverActions: {
      // Default is 1MB — too small for the admin tour editor's image
      // uploads (lib/actions/uploads.ts caps individual files at 8MB).
      bodySizeLimit: "10mb",
    },
  },
  images: {
    remotePatterns: [
      // Admin-uploaded tour photos (lib/actions/uploads.ts).
      { protocol: "https", hostname: "firebasestorage.googleapis.com", pathname: "/v0/b/**" },
      // Placeholder stock photography used when a tour has no uploaded image yet.
      { protocol: "https", hostname: "lh3.googleusercontent.com", pathname: "/**" },
    ],
  },
  // Old keshertours.com URLs (from the Search Console export) that still
  // carry search traffic — regenerated by scripts/migrate/generate-redirects.ts,
  // not hand-edited. See that script for the targeting rules.
  async redirects() {
    return legacyRedirects;
  },
};

export default nextConfig;
