import { config } from "dotenv";
config({ path: ".env.local" });
import { cert, initializeApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { writeFileSync } from "node:fs";
import type { Tour, BlogPost } from "../../lib/types";
import allPages from "./all-pages.json";

/**
 * Generates the full old-site -> new-site 301 redirect map from the GSC
 * "Top pages" export, per Eran's rules (2026-09):
 *  - /guides/* -> home
 *  - destination/type hub pages -> home, with a country-filter query where
 *    a clean match exists
 *  - everything else with real traffic -> home or the closest equivalent
 *    page (a country match, a migrated blog post, the tours/testimonials
 *    listing) rather than a blanket redirect
 *
 * Output is a static JSON file (lib/data/legacyRedirects.json) rather than
 * a live DB query at build time — it's regenerated by re-running this
 * script, the same way tours.seed.ts is a frozen snapshot rather than a
 * live read.
 *
 * Run with: npx tsx scripts/migrate/generate-redirects.ts
 */

const CLICK_THRESHOLD = 20;

// Old site's /tours-destinations/<continent>/<slug>/ country pages, mapped
// to the exact COUNTRIES enum values so the redirect matches a real filter.
// null = no clean 1:1 country match (a territory, not its own COUNTRIES
// entry) — falls back to home instead of a wrong/misleading filter.
const COUNTRY_SLUG_MAP: Record<string, string | null> = {
  egypt: "Egypt",
  morocco: "Morocco",
  "south-africa": "South Africa",
  tanzania: "Tanzania",
  cambodia: "Cambodia",
  china: "China",
  "hong-kong": null,
  india: "India",
  japan: "Japan",
  philippines: "Philippines",
  singapore: "Singapore",
  "south-korea": "South Korea",
  taiwan: "Taiwan",
  thailand: "Thailand",
  "united-arab-emirates": "United Arab Emirates",
  uzbekistan: "Uzbekistan",
  vietnam: "Vietnam",
  australia: "Australia",
  "new-zealand": "New Zealand",
  tasmania: "Australia",
  austria: "Austria",
  belgium: "Belgium",
  "canary-islands": "Spain",
  croatia: "Croatia",
  "czech-republic": "Czechia",
  denmark: "Denmark",
  england: "United Kingdom",
  finland: "Finland",
  france: "France",
  germany: "Germany",
  greece: "Greece",
  hungary: "Hungary",
  iceland: "Iceland",
  ireland: "Ireland",
  italy: "Italy",
  lithuania: "Lithuania",
  netherlands: "Netherlands",
  norway: "Norway",
  poland: "Poland",
  portugal: "Portugal",
  russia: "Russia",
  slovania: "Slovenia",
  spain: "Spain",
  sweden: "Sweden",
  alaska: "United States",
  canada: "Canada",
  usa: "United States",
  argentina: "Argentina",
  brazil: "Brazil",
  chile: "Chile",
  "costa-rica": "Costa Rica",
  ecuador: "Ecuador",
  "falkland-islands": null,
  "galapagos-islands": "Ecuador",
  guatemala: "Guatemala",
  panama: "Panama",
  peru: "Peru",
  uruguay: "Uruguay",
};

function countryUrl(countries: string[]): string {
  const qs = countries.map((c) => `country=${encodeURIComponent(c)}`).join("&");
  return `/?${qs}#featured-tours`;
}

interface Redirect {
  source: string;
  destination: string;
  permanent: true;
  note: string;
}

async function main() {
  const app = initializeApp({
    credential: cert({
      projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
      clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
      privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g, "\n"),
    }),
  });
  const db = getFirestore(app);

  const toursSnap = await db.collection("tours").get();
  const tours = toursSnap.docs.map((d) => d.data() as Tour);
  const published = tours.filter((t) => t.status === "published");
  const publishedSlugs = new Set(published.map((t) => t.slug));
  const publishedCountryToSlug = new Map<string, string>();
  for (const t of published) {
    for (const c of t.countries ?? []) {
      if (!publishedCountryToSlug.has(c)) publishedCountryToSlug.set(c, t.slug);
    }
  }
  const archivedBySlug = new Map(tours.filter((t) => t.status === "archived").map((t) => [t.slug, t]));

  const blogSnap = await db.collection("blogPosts").get();
  const blogSlugs = new Set(blogSnap.docs.map((d) => (d.data() as BlogPost).slug));

  // Build continent -> [countries] from the country pages actually seen
  // under it in the export, for the continent-level hub redirect.
  const continentCountries = new Map<string, Set<string>>();
  for (const row of allPages as { path: string; clicks: number }[]) {
    const m = row.path.match(/^\/tours-destinations\/([^/]+)\/([^/]+)\/?$/);
    if (!m) continue;
    const country = COUNTRY_SLUG_MAP[m[2]];
    if (!country) continue;
    if (!continentCountries.has(m[1])) continentCountries.set(m[1], new Set());
    continentCountries.get(m[1])!.add(country);
  }

  const redirects: Redirect[] = [];
  const skipped: { path: string; clicks: number; reason: string }[] = [];
  const seen = new Set<string>();

  const add = (source: string, destination: string, note: string) => {
    // Next's default trailingSlash:false config auto-redirects "/x/" -> "/x"
    // via its own internal, higher-priority redirect *before* checking these
    // custom ones — so a source that still has the trailing slash never
    // matches the (already-stripped) incoming request and 404s.
    const normalized = source.length > 1 && source.endsWith("/") ? source.slice(0, -1) : source;
    // Browsers send non-ASCII paths percent-encoded, and Next matches the
    // encoded pathname — a source with literal Hebrew characters (the
    // /guides/<name> and /טיולים/<slug> pages) compiles to a regex that can
    // never match, so those URLs 404 instead of redirecting.
    const encoded = encodeURI(normalized);
    if (seen.has(encoded)) return;
    seen.add(encoded);
    redirects.push({ source: encoded, destination, permanent: true, note });
  };

  for (const row of allPages as { path: string; clicks: number }[]) {
    let path = row.path;
    if (!path.startsWith("/")) path = "/" + path;
    if (path === "/" || path === "") continue; // home itself

    // 1. Guides — explicit rule: always to home, regardless of clicks or
    // whether the slug is Hebrew (checked before the non-ASCII filter below,
    // since this rule doesn't need to parse the slug at all).
    if (/^\/guides\//.test(path)) {
      add(path, "/", "guide profile page (feature not rebuilt) -> home");
      continue;
    }

    // Small set of known old-URL variants with an obvious new-site target,
    // found by spot-checking what the generic rules below left unmatched.
    const EXPLICIT_ALIASES: Record<string, string> = {
      "/terms-conditions/": "/legal/terms-conditions",
      "/contact-us/": "/contact",
      "/recommendations/": "/testimonials",
      "/category/blog/": "/blog",
      "/japan/": "/tours/japan",
    };
    if (EXPLICIT_ALIASES[path]) {
      add(path, EXPLICIT_ALIASES[path], "known old-URL alias");
      continue;
    }
    // Old site's Hebrew-mirror /טיולים/<slug>/ tour pages — same targeting as
    // the English /tours/<slug>/ rule below, just a different URL prefix.
    const hebrewTourMatch = path.match(/^\/טיולים\/([^/]+)\/?$/);
    if (hebrewTourMatch) {
      const slug = hebrewTourMatch[1];
      if (publishedSlugs.has(slug)) {
        add(path, `/tours/${slug}`, "Hebrew-mirror tour page -> live English tour page");
      } else {
        const archived = archivedBySlug.get(slug);
        const matchSlug = archived && (archived.countries ?? []).map((c) => publishedCountryToSlug.get(c)).find(Boolean);
        add(path, matchSlug ? `/tours/${matchSlug}` : "/", "Hebrew-mirror tour page");
      }
      continue;
    }

    // Non-ASCII / garbled slugs left over (encoding artifacts in the export) — skip.
    // eslint-disable-next-line no-control-regex
    if (/[^\x00-\x7F]/.test(path)) {
      skipped.push({ path, clicks: row.clicks, reason: "non-ascii/garbled slug" });
      continue;
    }

    // 2. Destination hub pages
    const contMatch = path.match(/^\/tours-destinations\/([^/]+)\/?$/);
    if (contMatch) {
      const countries = Array.from(continentCountries.get(contMatch[1]) ?? []);
      add(path, countries.length > 0 ? countryUrl(countries) : "/", "continent hub -> home w/ country filter");
      continue;
    }
    const countryMatch = path.match(/^\/tours-destinations\/[^/]+\/([^/]+)\/?$/);
    if (countryMatch) {
      const country = COUNTRY_SLUG_MAP[countryMatch[1]];
      add(path, country ? countryUrl([country]) : "/", country ? `destination hub -> ${country} filter` : "destination hub, no country match -> home");
      continue;
    }

    // 3. Tour-type hub pages — no equivalent filter on the new site.
    if (/^\/tours-types\/[^/]+\/?$/.test(path)) {
      add(path, "/", "tour-type hub (no equivalent filter) -> home");
      continue;
    }

    // 4. Individual tour pages
    const tourMatch = path.match(/^\/tours\/([^/]+)\/?$/);
    if (tourMatch) {
      const slug = tourMatch[1];
      if (publishedSlugs.has(slug)) continue; // resolves natively, no redirect needed
      const archived = archivedBySlug.get(slug);
      if (archived) {
        const matchSlug = (archived.countries ?? []).map((c) => publishedCountryToSlug.get(c)).find(Boolean);
        add(path, matchSlug ? `/tours/${matchSlug}` : "/", matchSlug ? `archived tour -> live ${matchSlug} (same country)` : "archived tour, no live country match -> home");
      } else {
        add(path, "/", "unmatched tour slug -> home");
      }
      continue;
    }

    // 5. Testimonials (old site misspells it "testemonials" on most pages,
    // but not all — e.g. /testimonials-morocco/ uses the correct spelling)
    if (/^\/test[ei]monials(-[^/]+)?\/?$/.test(path)) {
      add(path, "/testimonials", "old testimonials page -> /testimonials");
      continue;
    }

    // 6. All-tours listing
    if (path === "/all-tours/") {
      add(path, "/", "old all-tours listing -> home");
      continue;
    }

    // 7. wp-content assets — only worth a redirect if they carried real traffic.
    if (path.startsWith("/wp-content/")) {
      if (row.clicks > CLICK_THRESHOLD) {
        add(path, "/", `wp-content asset with ${row.clicks} clicks -> home (file itself not re-hosted at this URL)`);
      } else {
        skipped.push({ path, clicks: row.clicks, reason: "wp-content asset, low traffic" });
      }
      continue;
    }

    // 8. Root-level slug that matches a migrated blog post exactly.
    const rootSlug = path.replace(/^\//, "").replace(/\/$/, "");
    if (blogSlugs.has(rootSlug)) {
      add(path, `/blog/${rootSlug}`, "matches migrated blog post -> /blog/<slug> (once that route ships)");
      continue;
    }

    // 9. Pages that already exist at the same path on the new site — no redirect needed.
    if (["/contact/", "/special-offers/", "/faq/", "/about/", "/custom-made-tours/"].includes(path)) continue;

    // 10. Everything else: only worth a redirect above the click threshold; below it, skip.
    if (row.clicks > CLICK_THRESHOLD) {
      add(path, "/", `unclassified page with ${row.clicks} clicks -> home`);
    } else {
      skipped.push({ path, clicks: row.clicks, reason: "unclassified, low traffic" });
    }
  }

  redirects.sort((a, b) => a.source.localeCompare(b.source));

  writeFileSync(
    "lib/data/legacyRedirects.json",
    JSON.stringify(
      redirects.map(({ source, destination, permanent }) => ({ source, destination, permanent })),
      null,
      2
    ),
    "utf-8"
  );
  writeFileSync("scripts/migrate/output/redirects-full.json", JSON.stringify(redirects, null, 2), "utf-8");
  writeFileSync("scripts/migrate/output/redirects-skipped.json", JSON.stringify(skipped, null, 2), "utf-8");

  console.log(`Generated ${redirects.length} redirects -> lib/data/legacyRedirects.json`);
  console.log(`Skipped ${skipped.length} low-traffic/unmatched pages (no redirect) -> scripts/migrate/output/redirects-skipped.json`);
  console.log(`Full annotated list -> scripts/migrate/output/redirects-full.json`);
}
main().catch((e) => {
  console.error(e);
  process.exit(1);
});
